First raw version
fortizpenaloza/Nap pull request #17
Opened 2020-11-04 13:16 UTC by fortizpenaloza

2021-01-28 19:17 UTC, mtabacman requested changes

2021-01-28 19:17 UTC, mtabacman commented on source/Superluminal-RESTfulAPI-Tests/CacheRepositoryTest.class.st
> +	self shouldnt: [ repository remove: 'key' ] raise: KeyNotFound
This is not testing the expected method

2021-01-28 19:17 UTC, mtabacman commented on source/Superluminal-RESTfulAPI-Tests/CacheRepositoryTest.class.st
> +	self should: [ repository get: 'key' ] raise: KeyNotFound
it would be best to use should:raise:withMessageText: (the same goes for other tests)

2021-01-28 19:17 UTC, mtabacman commented on source/Superluminal-RESTfulAPI-Tests/CacheRepositoryTest.class.st
> +CacheRepositoryTest >> testSet [
shouldn't it be name testStoreAt ?

2021-01-28 19:17 UTC, mtabacman commented on source/Superluminal-RESTfulAPI-Tests/CacheRepositoryTest.class.st
> +		'currentDateTime',
what's the difference between dateTime and currentDateTime ? are all of these required in the superclass? couldn't they be left as subclass responsibility methonds and implemented by subclasses when required?

2021-01-28 19:17 UTC, mtabacman commented on source/Superluminal-RESTfulAPI-Tests/ExpiringResourceTest.class.st
> +
There are many similar tests, the common code could be extracted, and maybe even leave only one test that calls many times with different collaborators the extracted code.

2021-01-28 19:17 UTC, mtabacman commented on source/Superluminal-RESTfulAPI-Tests/LocalMemoryCacheRepositoryTest.class.st
> +{ #category : #'as yet unclassified' }
uncategorized method

2021-01-28 19:17 UTC, mtabacman commented on source/Superluminal-RESTfulAPI/LocalMemoryCacheRepository.class.st
> +	^ timeSourceProvider value
if the block provides `now` it's not a timeSourceProvider, but rather a nowProvider or a currentTimeProvider

2021-01-28 19:17 UTC, mtabacman commented on source/Superluminal-RESTfulAPI/MDCacheClient.extension.st
> +	self halt.
why is there a halt in the code????

2021-01-28 20:34 UTC, fortizpenaloza commented on source/Superluminal-RESTfulAPI-Tests/CacheRepositoryTest.class.st
> +		'currentDateTime',
There's no difference, it's old code that I forgot to change. It must look like `ExpiringCacheTest`

2021-02-03 11:19 UTC, mtabacman approved these changes, later dismissed

2021-02-06 12:05 UTC, mtabacman approved these changes

2021-02-07 13:55 UTC, gcotelli approved these changes

2021-02-08 03:59 UTC, merged