Added support for multi-part body content
fortizpenaloza/Nap pull request #44
Opened 2021-09-09 19:06 UTC by mtabacman

2021-09-09 21:07 UTC, fortizpenaloza requested changes

2021-09-09 21:07 UTC, fortizpenaloza commented on source/Superluminal-Model-Tests/AddMultiPartCommandTest.class.st
> +	ZnFileSystemUtils deleteIfExists: 'testApplyOnWhenAttachingFiles.txt'.
I suggest to perform an extract method a method named `#onFileNamed:withContents:assert:`

```smalltalk
self onFileNamed: 'testApplyOnWhenAttachingFiles.txt' withContents: '0123456789' assert: [:fileName :contents | 
  command := AddMultiPartCommand named: 'file' attaching: fileName  asFileReference.
  command applyOn: httpClient.

 	self
 		assert: httpClient request contentType main equals: 'multipart';
 		assert: httpClient request contentType sub equals: 'form-data'.

 	self assert: ( httpClient request entity partNamed: 'file' ) fieldValue equals: contents
 ]
```   

Do the same refactoring to the other methods.

2021-09-10 12:55 UTC, fortizpenaloza approved these changes, later dismissed

2021-09-10 12:55 UTC, fortizpenaloza commented on source/Superluminal-Model-Tests/TestAsserter.extension.st
> +TestAsserter >> withFileNamed: aFileName containing: aContents do: aBlock [
You clearly chose a better name 👏

2021-09-10 16:06 UTC, gcotelli approved these changes

2021-09-10 16:12 UTC, merged